  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    'google',
    'plugin:react/recommended',
  ],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  plugins: [
    'react',
  ],
  rules: {
    'indent': ['error', 2], // enforce 2 spaces for indentation
  },

