version: "3.8"

volumes:
  dist:

services:
  front-end:
    image: frontend
    restart: always
    networks:
      - connection
    volumes:
      - dist:/app/dist/cloudhub
    ports:
      - "8000:8000"
    command: npm run start  


  back-end:
    image: backend
    restart: always
    networks:
      - connection
    depends_on:
      - front-end
    command: python server.py runserver 0.0.0.0:8000   

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - dist:/var/www/web
    networks:
      - connection
    depends_on:
      - front-end
      - back-end
    command: nginx -g 'daemon off;'

networks:
  connection:
    external: true
