name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build backend
        run: |
           docker build -t back-end:latest ./backend

      - name: Build frontend
        run: |
           docker build -t front-end:latest .

      - name: Build nginx
        run: |
           docker build -t nginx:latest ./nginx

      - name: Login to Docker Hub 
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


      - name: Tag and push Docker images
        run: |
          sudo docker tag back-end-test:latest ${{ secrets.DOCKER_USERNAME }}/back-end-test:latest
          sudo docker tag front-end-test:latest ${{ secrets.DOCKER_USERNAME }}/front-end-test:latest
          sudo docker tag nginx-test:latest ${{ secrets.DOCKER_USERNAME }}/nginx-test:latest
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/back-end-test:latest
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/front-end-test:latest
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/nginx-test:latest
          
  deploy:
    runs-on: self-hosted
    steps:
          - name: deploying
            run: |
              sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
              cd /home/ubuntu/project
              sudo docker-compose up -d
