name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend
        run: docker build -t back-end:latest ./backend

      - name: Build frontend
        run: docker build -t front-end:latest .

      - name: Build nginx
        run: docker build -t nginx:latest ./nginx

      - name: Tag and push Docker images
        run: |
          docker tag back-end:latest ${{ secrets.DOCKER_USERNAME }}/back-end:latest
          docker tag front-end:latest ${{ secrets.DOCKER_USERNAME }}/front-end:latest
          docker tag nginx:latest ${{ secrets.DOCKER_USERNAME }}/nginx:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/back-end:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/front-end:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploying
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          cd /home/ubuntu/project
          docker-compose up -d
