name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build backend
        run: |
           docker build -t back-end:latest ./Back-end

      - name: Build frontend
        run: |
           docker build -t front-end:latest ./Front-end

      - name: Build nginx
        run: |
           docker build -t nginx:latest .

      - name: Login to Docker Hub
        run: 
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push Docker images
        run: |
          sudo docker tag back-end:latest ${{ secrets.DOCKER_USERNAME }}/back-end:latest
          sudo docker tag front-end:latest ${{ secrets.DOCKER_USERNAME }}/front-end:latest
          sudo docker tag nginx:latest ${{ secrets.DOCKER_USERNAME }}/nginx:latest
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/back-end:latest
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/front-end:latest
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest
          
  deploy:
    runs-on: self-hosted
    steps:
          - name: deploying
            run: |
              sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
              cd /home/ubuntu/project
              sudo docker-compose up -d
