name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build backend
        run: docker build -t back-end:latest ./backend

      - name: Build frontend
        run: docker build -t front-end:latest .

      - name: Build nginx
        run: docker build -t nginx:latest ./nginx

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
             
      - name: Tag and push Docker images
        run: |
          sudo docker tag back-end:latest test/back-end:latest
          sudo docker tag front-end:latest test/front-end:latest
          sudo docker tag nginx:latest test/nginx:latest
          
          sudo docker push test/back-end:latest
          sudo docker push test/front-end:latest
          sudo docker push test/nginx:latest
          
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploying
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          cd /home/ubuntu/project
          docker-compose up -d
